# Logging Configuration for MirCrew Indexer
version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(levelname)s: %(message)s'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  # Optional file handler - commented out for now
  # file:
  #   class: logging.FileHandler
  #   level: INFO
  #   formatter: detailed
  #   filename: logs/mircrew.log
  #   encoding: utf-8

loggers:
  mircrew:
    level: INFO
    handlers: [console]
    propagate: false

  mircrew.api:
    level: INFO
    handlers: [console]
    propagate: false

  mircrew.core:
    level: INFO
    handlers: [console]
    propagate: false

  mircrew.utils:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]